# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Johann Huang
email: isjohnwong@gmail.com
description: > 
  Focusing on web and data analysis.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://happyjohann.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  happyjohann
disqus_shortname: happyjohann

# Build settings
timezone: Asia/Shanghai
encoding: UTF-8
future: true
excerpt_separator: <!--more-->

comments: true

gems:
  - jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge